# Auto-generated by scripts/release.sh from homebrew/dimswitch.rb.template.
# Edit the template, not this file. The static fields (desc, zap paths,
# macOS minimum) live in the template; version / sha256 / url are filled
# in per release.
#
# Note: cask is named "dimswitch" (marketing name) but the .app bundle and
# bundle ID still use "Dimmer" — those are baked into the signed/notarized
# binary and the persisted UserDefaults domain.

cask "dimswitch" do
  version "1.1.0"
  sha256 "ec09bbca90c73d7731500f3303db6a0d00cb1592c67c756a6825b238b4c00aa4"

  url "https://frn-dist.sfo3.digitaloceanspaces.com/dimmer/1.1.0/Dimmer-1.1.0.dmg"
  name "Dimswitch"
  desc "Attention-driven brightness control for external displays via DDC/CI"
  # Source repo (johnathan-greenaway/vibrance) is private, so we point at
  # the public landing site instead — github.com/.../vibrance would 404 for
  # anyone running `brew info`.
  homepage "https://dimswitch.frnds.store"

  # Minimum macOS — keep in sync with LSMinimumSystemVersion in Info.plist
  # and the deployment target in Package.swift.
  depends_on macos: ">= :sonoma"

  app "Dimmer.app"

  # zap removes everything the app writes outside its bundle. Per Homebrew
  # Cask convention, uninstall just removes the .app; zap is invoked via
  # `brew uninstall --zap dimswitch` for a clean wipe.
  zap trash: [
    "~/Library/Preferences/com.dimmerapp.Dimmer.plist",
    "~/Library/Application Support/Dimmer",
    "~/Library/Caches/com.dimmerapp.Dimmer",
    "~/Library/Saved Application State/com.dimmerapp.Dimmer.savedState",
    "~/Library/HTTPStorages/com.dimmerapp.Dimmer",
  ]
end
