# Auto-generated by scripts/upload-dist.js from homebrew/dimswitch.formula.rb.template
# whenever a Linux AppImage is published alongside a release. Edit the
# template, not the generated file.
#
# This formula is the Linux counterpart to Casks/dimswitch.rb. Homebrew casks
# are macOS-only, so Linux users (Linuxbrew) install via `brew install
# dimswitch` (no --cask). On macOS, `brew install dimswitch` is redirected to
# the cask via odie below — there's no formula-installable build for macOS.
#
# The Linux build is the Rust port under cross-platform/, packaged as a
# self-mounting AppImage. We download it to libexec, mark it executable, and
# expose a `dimswitch` shim in bin/ that execs the AppImage.

class Dimswitch < Formula
  desc "Attention-driven brightness control for external displays via DDC/CI"
  # Source repo is private; point at the public landing site instead.
  homepage "https://dimswitch.frnds.store"
  version "1.1.16"
  license "Proprietary"

  on_macos do
    odie <<~EOS
      The Linux formula was selected, but you're on macOS. Use the cask:

          brew install --cask dimswitch

      (Dimswitch on macOS ships as a notarized .app bundle; the cask is the
      only supported path. The formula is Linux-only.)
    EOS
  end

  on_linux do
    on_intel do
      # `#{version}` interpolation matches the cask. Formula audit doesn't
      # require `verified:` the way cask audit does.
      url "https://frn-dist.sfo3.digitaloceanspaces.com/dimmer/#{version}/Dimmer-#{version}-linux-x86_64.AppImage"
      sha256 "4a30a39090d5f0df7fb3e3cd889b2ee4b9d6551c175ff0aa7fe369bf70c92c3a"
    end
    on_arm do
      odie <<~EOS
        No aarch64 Linux build is published yet.
        Reach out via https://dimswitch.frnds.store if you'd like one.
      EOS
    end
  end

  def install
    # AppImage is a self-mounting executable; nothing to extract. We stash it
    # under libexec and write a tiny shim in bin/ so users get `dimswitch`
    # on PATH without having to chmod or hunt down the AppImage.
    libexec.install Dir["*.AppImage"].first => "Dimmer.AppImage"
    chmod 0755, libexec/"Dimmer.AppImage"
    (bin/"dimswitch").write <<~SH
      #!/bin/sh
      exec "#{libexec}/Dimmer.AppImage" "$@"
    SH
    chmod 0755, bin/"dimswitch"
  end

  def caveats
    <<~EOS
      Dimswitch on Linux uses DDC/CI over i2c-dev. You'll likely need:

        sudo modprobe i2c-dev
        sudo usermod -aG i2c $USER   # then log out + back in

      Run with `dimswitch` once installed.
    EOS
  end

  test do
    # The full app needs a display and i2c; we can't drive it in `brew test`.
    # Just verify the install put a working executable shim on PATH — the
    # cross-platform binary itself is exercised by its own test suite.
    assert_predicate bin/"dimswitch", :executable?
  end
end
